### ISSUE TITLE
1.8.2 Bugfix/Feature Tracking

### ISSUE THREAD

**Issue by coloursofnoise** [CommunalHelper/CommunalHelper#43]
## Bugs
- [x] ConnectedMoveBlock doesn't support custom texture even though it has the option for it.
- [x] You can jump out of the dream bubble state - 3a4073c25c2c5fe1c2102604c034bad23f4ef352
- [x] Weird liftspeed issues with cassette zip movers that turn off (possibly jumpfixcontroller-related?) - 0bf1d43830ba5fb3b329259c9fbdb7875a7af0e1
- [x] ~~Timed Trigger Spikes dust variant has missing textures~~  - Hidden in 1.8.2, pushed back to 1.9.0

## Additions
- [x] Add support for ConnectedMoveBlock reskinning/recoloring
- [x] Add note about ConnectedSolids reskin template in tooltips
- [x] Music Param Trigger - 3e96cf8358496838f0ba7dab6833212e9e01f3e2
- [x] ~~Cassette block controller: Change CassetteBlock Colour and behaviour in a room (BrokemiaHelper CassetteDreamBlocks too?)~~ - Pushed back to 1.9.0
